# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L0XMHqPPihKtcnqdIwpRB1FcxiFMx537
"""

import streamlit as st
from ultralytics import YOLO
from PIL import Image

# Load model
model = YOLO("best.pt")

st.title("🚗 Vehicle Detection App")
st.write("Upload gambar dan sistem akan mendeteksi Car, Bus, dan Van.")

uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

if uploaded_file:
    # Buka gambar
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Original Image", use_column_width=True)

    st.write("Processing...")
    # Lakukan deteksi
    results = model(image)

    # Tampilkan gambar hasil deteksi
    detected_img = results[0].plot()  # .plot() membuat gambar dengan Bounding Box
    st.image(detected_img, caption="Detection Result", use_column_width=True)

    # Hitung jumlah objek
    class_ids = results[0].boxes.cls.tolist()
    names = model.names
    count = {}

    for cls_id in class_ids:
        class_name = names[int(cls_id)]
        count[class_name] = count.get(class_name, 0) + 1

    st.subheader("Kesimpulan Deteksi:")
    if len(count) == 0:
        st.write("❌ Tidak ada kendaraan terdeteksi.")
    else:
        for obj, total in count.items():
            st.write(f"- **{obj.capitalize()}**: {total}")

        #satu kalimat ringkas:
        summary_sentence = ", ".join([f"{total} {obj}(s)" for obj, total in count.items()])
        st.write(f"➡️ Pada gambar ini terdeteksi: **{summary_sentence}.**")